docs: Update docs
vivliostyle/themes pull request #135
Opened 2024-10-04 07:30 UTC by spring-raining

2024-12-05 03:25 UTC, MurakamiShinyu commented
チェックしました。遅くなってすみません！

素晴らしいです。各テーマにサンプル組版結果イメージが作られるところなど。

ひとつ気になっているところですが、ドキュメントのURLについて、確認です：

次のところに、従来のテーマのドキュメントのURL（`https://vivliostyle.github.io/themes/#/spec` など）が残っています：

https://github.com/vivliostyle/themes/blob/c2f917cc9fcf7fdac67a1f13fd41f6f246a11da8/CONTRIBUTING.md?plain=1#L14

https://github.com/vivliostyle/themes/blob/c2f917cc9fcf7fdac67a1f13fd41f6f246a11da8/README.md?plain=1#L32

https://github.com/vivliostyle/themes/blob/c2f917cc9fcf7fdac67a1f13fd41f6f246a11da8/docs/official.md?plain=1#L10

https://github.com/vivliostyle/themes/blob/c2f917cc9fcf7fdac67a1f13fd41f6f246a11da8/docs/ja/official.md?plain=1#L10

これまでのGitHub Pages＋Docuteの利用をやめて、直接GitHubリポジトリ上のMDファイルをドキュメントのURLとするのであれば、

`https://vivliostyle.github.io/themes/#/spec`  
↓  
`https://github.com/vivliostyle/themes/blob/main/docs/spec.md`

`https://vivliostyle.github.io/themes/#/ja/spec`  
↓  
`https://github.com/vivliostyle/themes/blob/main/docs/ja/spec.md`

ですね？

2024-12-05 05:03 UTC, MurakamiShinyu requested changes
> 次のところに、従来のテーマのドキュメントのURL（https://vivliostyle.github.io/themes/#/spec など）が残っています：

これのほかはapproveです！

2024-12-07 01:50 UTC, spring-raining commented
こちらで修正しました:+1: 070a00b5c97916432b47903c1e99d0d196273bd4

2024-12-07 01:53 UTC, MurakamiShinyu approved these changes
💯

2024-12-07 01:56 UTC, merged